[project]
name = "econ6912-replication"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.2",
    "numpy>=2.1.0",
    "pip>=24.2",
    "ipykernel>=6.29.5",
    "jupyterlab>=4.2.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
